---
- name: Create instances
  hosts: general
  gather_facts: no
  connection: local
  vars_files:
    - vars/instance/instance_var.yml
  tasks:
    - include_tasks: roles/instance/tasks/create.yml
      run_once: true

- name: Setup instances
  hosts: general
  become: yes
  become_user: root
  gather_facts: no
  tasks: 
    - include_tasks: roles/instance/tasks/setup.yml

- name: Install Monitor
  hosts: general
  become: yes
  become_user: root
  gather_facts: no
  vars_files:
    - vars/monitor/monitor_var.yml
  tasks:
    - include_tasks: roles/monitor/tasks/main.yml

- name: Install Google Ops Agent
  hosts: general
  become: yes
  become_user: root
  gather_facts: no
  tasks:
    - include_tasks: roles/ops_agent/tasks/main.yml
